kubespray: 2.14 -> 2.15
wireapp/wire-server-deploy pull request #417
Opened 2021-02-05 13:45 UTC by arianvp

This is 2.15 with https://github.com/kubernetes-sigs/kubespray/pull/7247
cherry-picked on top; as we need it for offline deploy.

It will allow us to point the docker install playbook to an alternative
package repository.

Though 2.14 we never had in a release, I will still provide some upgrade
instructions:

To upgrade an existing cluster follow the instructions here:
https://kubespray.io/#/docs/upgrades?id=graceful-upgrade

```
$ cd ansible
$ ansible-playbook ./roles-external/kubespray/upgrade-cluster.yml -i ./your-inventory
```

This should guide you through the upgrade process step by step.

2021-02-08 08:56 UTC, arianvp commented
I made a backport PR for the required fix upstream. https://github.com/kubernetes-sigs/kubespray/pull/7263

2021-02-15 10:37 UTC, jmatsushita requested changes

2021-02-15 10:37 UTC, jmatsushita commented on CHANGELOG.md
> +  and kubernetes 1.97.7. This allows us to use Kubespray's support for offline deployments
1.19.7

2021-02-15 10:39 UTC, arianvp commented on CHANGELOG.md
> +  and kubernetes 1.97.7. This allows us to use Kubespray's support for offline deployments
```suggestion
  and kubernetes 1.19.7. This allows us to use Kubespray's support for offline deployments
```

2021-02-15 11:11 UTC, jmatsushita approved these changes

2021-02-15 11:32 UTC, merged