Fix ansible module dependencies
wireapp/wire-server-deploy pull request #443
Opened 2021-04-01 09:09 UTC by arianvp

What we were doing before was way too complicated. Ansible itself
doesn't have any dependency on boto to function. The _target host_
needs to have boto installed.

In our case the target host is 'localhost'.  Ansible will by default
pick /usr/bin/python3 as the python interpreter ogit n target hosts but of
course we can't rely on that having boto installed.

Instead, we configure ansible_python_interpreter to point to the
environment we built with nix; which contains a python that has boto
installed.

This way boto can be found and the playbooks should succeed!

2021-04-01 19:04 UTC, lucendio approved these changes
LGTM but DH action for macos does not agree.

2021-04-01 21:00 UTC, arianvp commented
This fixes it locally but it's still broken in the dockerfile. I'll try to get that to work Tuesday first

2021-04-06 08:44 UTC, arianvp commented
I tested this with the following playbook:

```ansible
- hosts: localhost
  gather_facts: yes
  serial: 1
  become: no
  tasks:
    - debug: var=ansible_python_interpreter
    - debug: var=ansible_python_version
    - debug: var=ansible_playbook_python
    - aws_s3:
        mode: list
        bucket: public.wire.com
```

2021-04-06 10:05 UTC, lucendio requested changes

2021-04-06 10:05 UTC, lucendio commented on ansible/host_vars/localhost/python.yml
> +ansible_python_interpreter: $LOCALHOST_PYTHON
For me, this fails with:
```
PLAY [localhost] **********************************************

TASK [Gathering Facts] **********************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}}, "msg": "The following modules failed to execute: setup\n"}

PLAY RECAP **********************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

What you probably want to do is
```suggestion
ansible_python_interpreter: "{{ lookup('env','LOCALHOST_PYTHON') }}"
```
or maybe even add a default in addition, if you think it makes sense:
```
ansible_python_interpreter: "{{ lookup('env','LOCALHOST_PYTHON') | default('/some/path') }}"
```

2021-04-06 10:34 UTC, lucendio approved these changes

2021-04-06 10:35 UTC, merged