add deeplinks vars in nginz config of wire-server prod-values example
wireapp/wire-server-deploy pull request #598
Opened 2023-01-09 18:57 UTC by amitsagtani97

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2023-01-10 09:57 UTC, julialongtin requested changes

2023-01-10 09:57 UTC, julialongtin commented on values/wire-server/prod-values.example.yaml
> +        host: "socks5.proxy.com"
```suggestion
        ##### Uncomment these if you want to direct your users into using a proxy 
        # host: "socks5.proxy.com"
```

2023-01-10 09:57 UTC, julialongtin commented on values/wire-server/prod-values.example.yaml
> +        port: 1080
```suggestion
        # port: 1080
```

2023-01-10 09:57 UTC, julialongtin commented on values/wire-server/prod-values.example.yaml
> +        needsAuthentication: true
```suggestion
        # needsAuthentication: true
```

2023-01-11 08:27 UTC, amitsagtani97 commented on values/wire-server/prod-values.example.yaml
> +      title: "My Custom Wire Backend"
makes sense, fixed.

2023-01-12 13:10 UTC, julialongtin commented on values/wire-server/prod-values.example.yaml
> +      apiProxy: # (optional)
```suggestion
      # Optional -- Uncomment these if you want to direct all of your mobile users to use the same proxy.
      #apiProxy:
```

2023-01-12 13:11 UTC, julialongtin commented on values/wire-server/prod-values.example.yaml
> +        ##### Uncomment these if you want to direct your users into using a proxy
```suggestion
```

2023-01-12 13:13 UTC, merged