bump terraform version to 1.0
wireapp/wire-server-deploy pull request #666
Opened 2023-10-11 21:20 UTC by amitsagtani97

Bump terraform version to 1.0

2023-10-11 23:16 UTC, amitsagtani97 commented
@julialongtin @supersven The last green CI was found to be working with v1.43.0 of hcloud module(https://registry.terraform.io/providers/hetznercloud/hcloud/latest)
the most recent version 1.44 onwards have a lot of changes which are not supported by many existing modules in our code.

Also, I tried to play around with different versions of terraform(0.14 and 1.0),  but it didn't worked. 
Looks like this is the good fix at the current set of dependencies(both internaland external like kubespray)

2023-10-13 09:09 UTC, supersven commented on offline/cd.sh
> +adminhost="${adminhost//\"/}"
Why is this needed? Has the output format of `terraform output` changed between versions (`0.13` -> `1.x`)?

2023-10-13 09:17 UTC, supersven requested changes
Thanks a lot for investigating in this!

- I think it would be good to cleanup the commit history (squash / drop / ...)
- We should have an answer for this: https://github.com/wireapp/wire-server-deploy/pull/666/files#r1357993681
- Are you sure that all Terraform usages still work? Or, does this PR need additional manual testing?

2023-10-13 18:06 UTC, amitsagtani97 commented
> Thanks a lot for investigating in this!
> 
> * I think it would be good to cleanup the commit history (squash / drop / ...)
> * We should have an answer for this: https://github.com/wireapp/wire-server-deploy/pull/666/files#r1357993681
> * Are you sure that all Terraform usages still work? Or, does this PR need additional manual testing?



> Thanks a lot for investigating in this!
> 
> * I think it would be good to cleanup the commit history (squash / drop / ...)
> * We should have an answer for this: https://github.com/wireapp/wire-server-deploy/pull/666/files#r1357993681
> * Are you sure that all Terraform usages still work? Or, does this PR need additional manual testing?

 - Fixed the history.
 - There were extra double quotes returned from the terraform output from the new version, so had to remove those.
 - As of now, I tried to run "terraform init" command in all the environment directory in the wire-server-deploy and it returned no warnings or error message.

2023-10-13 21:23 UTC, merged