introduce more automation for dedicated Hetzner server deployments prior to kubespray upgrades
wireapp/wire-server-deploy pull request #676
Opened 2024-01-17 16:57 UTC by jschumacher-wire

WPB-2324

Introduction of ansible playbook for Hetzner server bootstrapping; more automation for offline-vm-setup.sh

2024-01-17 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-server-deploy?pullRequest=676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-server-deploy?pullRequest=676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-server-deploy?pullRequest=676) it.</sub>

2024-01-18 08:02 UTC, e-lisa commented on ansible/hetzner-single-deploy.yml
> +    ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIODDzgw4BncNvSVOIraAXZYkkLn+iTo6ixkXXQ4lKZhL jan.schumacher@wire.com"
Should this be your personal public key?

2024-01-18 08:12 UTC, e-lisa commented on ansible/files/hetzner_server_sshd_config
Does this need to be its own static file in ansible, or can we copy the existing `sshd_config` and modify it with the ansible inline functionality?

2024-01-18 08:16 UTC, e-lisa commented on offline/single_hetzner_machine_installation.md
> +    ssh_pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIODDzgw4BncNvSVOIraAXZYkkLn+iTo6ixkXXQ4lKZhL jan.schumacher@wire.com"
might want to just change the key comment here and consider not using a valid key. i am sure a user might accidentally copy this one day :)

2024-01-18 13:20 UTC, supersven requested changes
I'm a bit confused why we're adding comments to commits instead of reviews... However, please take this into account: https://github.com/wireapp/wire-server-deploy/commit/7210a70e2ab342231bd5e39ccb8bd1235561f7e2#r137355832

2024-01-23 09:56 UTC, julialongtin requested changes

2024-01-23 09:56 UTC, julialongtin commented on ansible/files/hetzner_server_nftables.conf
> +#!/usr/sbin/nft -f
general question: why did you go with this method, rather than ufw rules?

2024-01-23 09:56 UTC, julialongtin commented on bin/offline-vm-setup.sh
> +msg ""
so, how do we get our 'usual' key from 1password into this?

2024-01-23 09:56 UTC, julialongtin commented on bin/offline-vm-setup.sh
> +    --ram 8192 \
not all machines need the same ram, diskspace.

2024-01-23 09:56 UTC, julialongtin commented on bin/offline-vm-setup.sh
> +    msg "Creating VM ""${VM_NAME[i]}"" with IP ""${VM_IP[i]}"" ..."
If we have to set this up again, we're going to have a LOT of duplicate entries in /etc/hosts

2024-01-23 09:56 UTC, julialongtin commented on offline/docs_ubuntu_22.04.md
> +This section is a continuation of the demo cluster setup described in single_hetzner_machine_installation.md. At this point, the following prerequisites should be met:
This document is certanly not a continuation: THIS IS WHERE CUSTOMERS START.

2024-01-23 09:56 UTC, julialongtin commented on offline/single_hetzner_machine_installation.md
> +Select Ubuntu 22.04.2 on an ax101 dedicated server. If possible, please already provide a public key in the Hetzner console which can be used for ansible deployment.
```suggestion
Select Ubuntu 22.04.2 on an ax101 dedicated server. Make sure you provide a public key in the Hetzner console which can be used for ansible deployment.
```

2024-01-23 09:56 UTC, julialongtin commented on offline/single_hetzner_machine_installation.md
> +Please note the public IP of the newly provisioned server, as it's used for the ansible playbook run.
we're both wrong. tell the user where to get the IP in the interface.

2024-01-23 09:56 UTC, julialongtin commented on offline/single_hetzner_machine_installation.md
> +Take a look at the "vars:" section in wire-server-deploy/ansible/hetzner-single-deploy.yml and adjust vars as needed. Example:
traditionally, we don't edit anything but the hosts.ini, in ansible/.

2024-01-23 09:56 UTC, julialongtin commented on offline/single_hetzner_machine_installation.md
> +VMs created with offline-vm-setup.sh are accessible via SSH with two public keys.
you might want to say where they're accessable from.

2024-01-23 09:59 UTC, julialongtin commented on ansible/files/hetzner_server_nftables.conf
> +#!/usr/sbin/nft -f
another point here: how do we (temporarily) turn on masquerading for this setup?

2024-01-23 10:01 UTC, julialongtin commented on offline/docs_ubuntu_22.04.md
> +This section is a continuation of the demo cluster setup described in single_hetzner_machine_installation.md. At this point, the following prerequisites should be met:
EG: in a customer deployment, we point them to this document, and follow along with them, or they follow along with us.

2024-01-23 11:32 UTC, julialongtin commented on bin/offline-vm-setup.sh
> +    --ram 8192 \
https://docs.google.com/document/d/1nX4K5Sdpb66NwsSDE_ppDMtYPvFop3IAzfKhUP2geLY/edit?usp=sharing

2024-01-24 15:49 UTC, julialongtin approved these changes

2024-01-24 15:58 UTC, merged